name: cmake

on: [push, pull_request, workflow_dispatch]

env:
  CMAKE_VERSION: 3.22.1
  BUILD_TYPE: Release
  CLIB_PATH: ${{ github.workspace }}/clib-latest
  DKU_PATH: ${{ github.workspace }}/dku
  
jobs:
  build:
    name: it-just-werks
    runs-on: windows-2022
    strategy:
      fail-fast: false
      
    steps:
      - name: checkout-self
        uses: actions/checkout@v2
        with:
          path: master
      
      - name: checkout-clib
        uses: actions/checkout@v2
        with:
          repository: Ryan-rsm-McKenzie/CommonLibSSE
          ref: master
          path: ${{ env.CLIB_PATH }}

      - name: checkout-dku
        uses: actions/checkout@v2
        with:
          repository: gottyduke/DKUtil
          path: ${{ env.DKU_PATH }}

      - name: vcpkg
        run: |
          & $env:VCPKG_INSTALLATION_ROOT\bootstrap-vcpkg.bat
        shell: pwsh
      
      - name: cache-vcpkg
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/cache
          key: msvc-artifact-${{ hashFiles('master/vcpkg.json') }}
      
      - name: build
        working-directory: ${{ github.workspace }}/master
        run: cmake -B Build -S . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DGITHUB_CI=1 -DANNIVERSARY_EDITION=1
        shell: pwsh
